// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::damm_v2::client::*;
use meteora_damm_v2_api_generated::apis::{
    pools_api,
    stats_api,
};
use meteora_damm_v2_api_generated::apis::Error;
use meteora_damm_v2_api_generated::models;

impl Pools {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_group(&self, lexical_order_mints: &str, page: Option<i32>, page_size: Option<i32>, query: Option<&str>, sort_by: Option<&str>, filter_by: Option<&str>) -> Result<models::PaginationResponsePoolResponse, Error<pools_api::GetGroupError>> {
        pools_api::get_group(&self.config, lexical_order_mints, page, page_size, query, sort_by, filter_by).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_groups(&self, page: Option<i32>, page_size: Option<i32>, query: Option<&str>, sort_by: Option<&str>, filter_by: Option<&str>, volume_tw: Option<&str>, fee_tvl_ratio_tw: Option<&str>) -> Result<models::PaginationResponseGroupResponse, Error<pools_api::GetGroupsError>> {
        pools_api::get_groups(&self.config, page, page_size, query, sort_by, filter_by, volume_tw, fee_tvl_ratio_tw).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_historical_volume(&self, address: &str, timeframe: Option<&str>, start_time: Option<i32>, end_time: Option<i32>) -> Result<models::TimeseriesResponseVolumeHistoryResponse, Error<pools_api::GetHistoricalVolumeError>> {
        pools_api::get_historical_volume(&self.config, address, timeframe, start_time, end_time).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_ohlcv(&self, address: &str, timeframe: Option<&str>, start_time: Option<i32>, end_time: Option<i32>) -> Result<models::TimeseriesResponseOhlcvResponse, Error<pools_api::GetOhlcvError>> {
        pools_api::get_ohlcv(&self.config, address, timeframe, start_time, end_time).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pool(&self, address: &str) -> Result<models::PoolResponse, Error<pools_api::GetPoolError>> {
        pools_api::get_pool(&self.config, address).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pools(&self, page: Option<i32>, page_size: Option<i32>, query: Option<&str>, sort_by: Option<&str>, filter_by: Option<&str>) -> Result<models::GetPools200Response, Error<pools_api::GetPoolsError>> {
        pools_api::get_pools(&self.config, page, page_size, query, sort_by, filter_by).await
    }
}

impl Stats {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_protocol_overview(&self) -> Result<models::ProtocolMetricsResponse, Error<stats_api::GetProtocolOverviewError>> {
        stats_api::get_protocol_overview(&self.config).await
    }
}
