// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::dlmm::client::*;
use meteora_dlmm_api_generated::apis::{
    limit_orders_api,
    pools_api,
    portfolio_api,
    positions_api,
    stats_api,
    wallets_api,
};
use meteora_dlmm_api_generated::apis::Error;
use meteora_dlmm_api_generated::models;

impl LimitOrders {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_bonus_claimed_for_pool(&self, wallet: &str, pool_address: &str) -> Result<models::BonusClaimedResponse, Error<limit_orders_api::GetBonusClaimedForPoolError>> {
        limit_orders_api::get_bonus_claimed_for_pool(&self.config, wallet, pool_address).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_closed_limit_order_pools(&self, wallet: &str, page: Option<i64>, page_size: Option<i64>) -> Result<models::PaginationResponseClosedLimitOrderPoolSummary, Error<limit_orders_api::GetClosedLimitOrderPoolsError>> {
        limit_orders_api::get_closed_limit_order_pools(&self.config, wallet, page, page_size).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_closed_limit_orders_for_pool(&self, wallet: &str, pool_address: &str, page: Option<i64>, page_size: Option<i64>) -> Result<models::ClosedLimitOrdersForPoolResponse, Error<limit_orders_api::GetClosedLimitOrdersForPoolError>> {
        limit_orders_api::get_closed_limit_orders_for_pool(&self.config, wallet, pool_address, page, page_size).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_limit_order_summary(&self, wallet: &str) -> Result<models::LimitOrderSummaryResponse, Error<limit_orders_api::GetLimitOrderSummaryError>> {
        limit_orders_api::get_limit_order_summary(&self.config, wallet).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_open_limit_order_pools(&self, wallet: &str, page: Option<i64>, page_size: Option<i64>) -> Result<models::PaginationResponseOpenLimitOrderPoolSummary, Error<limit_orders_api::GetOpenLimitOrderPoolsError>> {
        limit_orders_api::get_open_limit_order_pools(&self.config, wallet, page, page_size).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_open_limit_orders_for_pool(&self, wallet: &str, pool_address: &str, page: Option<i64>, page_size: Option<i64>) -> Result<models::OpenLimitOrdersForPoolResponse, Error<limit_orders_api::GetOpenLimitOrdersForPoolError>> {
        limit_orders_api::get_open_limit_orders_for_pool(&self.config, wallet, pool_address, page, page_size).await
    }
}

impl Pools {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_group(&self, lexical_order_mints: &str, page: Option<i32>, page_size: Option<i32>, query: Option<&str>, sort_by: Option<&str>, filter_by: Option<&str>) -> Result<models::PaginationResponsePoolResponse, Error<pools_api::GetGroupError>> {
        pools_api::get_group(&self.config, lexical_order_mints, page, page_size, query, sort_by, filter_by).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_groups(&self, page: Option<i32>, page_size: Option<i32>, query: Option<&str>, sort_by: Option<&str>, filter_by: Option<&str>, volume_tw: Option<&str>, fee_tvl_ratio_tw: Option<&str>) -> Result<models::PaginationResponseGroupResponse, Error<pools_api::GetGroupsError>> {
        pools_api::get_groups(&self.config, page, page_size, query, sort_by, filter_by, volume_tw, fee_tvl_ratio_tw).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_historical_volume(&self, address: &str, timeframe: Option<&str>, start_time: Option<i32>, end_time: Option<i32>) -> Result<models::TimeseriesResponseVolumeHistoryResponse, Error<pools_api::GetHistoricalVolumeError>> {
        pools_api::get_historical_volume(&self.config, address, timeframe, start_time, end_time).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_ohlcv(&self, address: &str, timeframe: Option<&str>, start_time: Option<i32>, end_time: Option<i32>) -> Result<models::TimeseriesResponseOhlcvResponse, Error<pools_api::GetOhlcvError>> {
        pools_api::get_ohlcv(&self.config, address, timeframe, start_time, end_time).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pool(&self, address: &str) -> Result<models::PoolResponse, Error<pools_api::GetPoolError>> {
        pools_api::get_pool(&self.config, address).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pools(&self, page: Option<i32>, page_size: Option<i32>, query: Option<&str>, sort_by: Option<&str>, filter_by: Option<&str>) -> Result<models::GetPools200Response, Error<pools_api::GetPoolsError>> {
        pools_api::get_pools(&self.config, page, page_size, query, sort_by, filter_by).await
    }
}

impl Portfolio {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_portfolio_total(&self, user: &str) -> Result<models::PortfolioTotalResponse, Error<portfolio_api::GetPortfolioTotalError>> {
        portfolio_api::get_portfolio_total(&self.config, user).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_user_open_portfolio(&self, user: &str, page: Option<i32>, page_size: Option<i32>, sort_direction: Option<models::SortDirection>, sort_by: Option<models::GetOpenPortfolioSort>) -> Result<models::GetOpenPortfolioResponse, Error<portfolio_api::GetUserOpenPortfolioError>> {
        portfolio_api::get_user_open_portfolio(&self.config, user, page, page_size, sort_direction, sort_by).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_user_portfolio(&self, user: &str, page: Option<i32>, page_size: Option<i32>, days_back: Option<i32>) -> Result<models::GetPortfolioResponse, Error<portfolio_api::GetUserPortfolioError>> {
        portfolio_api::get_user_portfolio(&self.config, user, page, page_size, days_back).await
    }
}

impl Positions {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_pool_position_pnl(&self, pool_address: &str, user: &str, status: Option<models::PositionStatus>, page: Option<i32>, page_size: Option<i32>) -> Result<models::GetPoolPositionPnLResponse, Error<positions_api::GetPoolPositionPnlError>> {
        positions_api::get_pool_position_pnl(&self.config, pool_address, user, status, page, page_size).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_position_historical_events(&self, address: &str, event_type: Option<&str>, order_direction: Option<&str>) -> Result<models::GetPositionHistoricalEventsResponse, Error<positions_api::GetPositionHistoricalEventsError>> {
        positions_api::get_position_historical_events(&self.config, address, event_type, order_direction).await
    }
}

impl Stats {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_protocol_overview(&self) -> Result<models::ProtocolMetricsResponse, Error<stats_api::GetProtocolOverviewError>> {
        stats_api::get_protocol_overview(&self.config).await
    }
}

impl Wallets {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_wallet_pool_total_claims(&self, wallet: &str, pool_address: &str) -> Result<models::GetWalletTotalClaimsResponse, Error<wallets_api::GetWalletPoolTotalClaimsError>> {
        wallets_api::get_wallet_pool_total_claims(&self.config, wallet, pool_address).await
    }
}
