// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::stake2earn::client::*;
use meteora_stake2earn_api_generated::apis::{
    analytics_api,
    vault_api,
};
use meteora_stake2earn_api_generated::apis::Error;
use meteora_stake2earn_api_generated::models;

impl Analytics {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_all_analytics(&self) -> Result<models::AggregateAnalyticInfo, Error<analytics_api::GetAllAnalyticsError>> {
        analytics_api::get_all_analytics(&self.config).await
    }
}

impl Vault {
    #[allow(clippy::too_many_arguments)]
    pub async fn filter_vaults(&self, pool_address: Option<Vec<String>>) -> Result<models::VaultsResponse, Error<vault_api::FilterVaultsError>> {
        vault_api::filter_vaults(&self.config, pool_address).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_all_vaults(&self) -> Result<models::VaultsResponse, Error<vault_api::GetAllVaultsError>> {
        vault_api::get_all_vaults(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_one_vault(&self, vault_address: &str) -> Result<models::VaultDetailWithLeaderboard, Error<vault_api::GetOneVaultError>> {
        vault_api::get_one_vault(&self.config, vault_address).await
    }
}
