// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::damm_v1::client::*;
use meteora_damm_v1_api_generated::apis::{
    alpha_vault_api,
    fee_configs_api,
    pools_api,
};
use meteora_damm_v1_api_generated::apis::Error;
use meteora_damm_v1_api_generated::models;

impl AlphaVault {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_all(&self) -> Result<models::AlphaVaultVaultConfigResponse, Error<alpha_vault_api::GetAllError>> {
        alpha_vault_api::get_all(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_vaults(&self, vault_address: Option<Vec<String>>, pool_address: Option<Vec<String>>, base_mint: Option<Vec<String>>) -> Result<Vec<models::AlphaVaultResponse>, Error<alpha_vault_api::GetVaultsError>> {
        alpha_vault_api::get_vaults(&self.config, vault_address, pool_address, base_mint).await
    }
}

impl FeeConfigs {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_config_associated_fee_configs(&self, config_address: &str) -> Result<Vec<models::FeeConfigResponse>, Error<fee_configs_api::GetConfigAssociatedFeeConfigsError>> {
        fee_configs_api::get_config_associated_fee_configs(&self.config, config_address).await
    }
}

impl Pools {
    #[allow(clippy::too_many_arguments)]
    pub async fn filter_and_get_pool_info(&self, page: i32, size: i32, filter: Option<&str>, sort_key: Option<models::PoolSortKey>, order_by: Option<models::OrderBy>, pools_to_top: Option<Vec<String>>, unknown: Option<bool>, pool_type: Option<models::PoolTypeQueryParam>, is_monitoring: Option<bool>, hide_low_tvl: Option<f64>, hide_low_apr: Option<bool>, include_token_mints: Option<Vec<String>>, include_pool_token_pairs: Option<Vec<String>>, launchpad: Option<Vec<String>>) -> Result<models::PaginatedPoolResponse, Error<pools_api::FilterAndGetPoolInfoError>> {
        pools_api::filter_and_get_pool_info(&self.config, page, size, filter, sort_key, order_by, pools_to_top, unknown, pool_type, is_monitoring, hide_low_tvl, hide_low_apr, include_token_mints, include_pool_token_pairs, launchpad).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn filter_and_get_pool_info_deprecated(&self, page: i32, size: i32, version: &str, filter: Option<&str>, sort_key: Option<&str>, order_by: Option<&str>, pools_to_top: Option<Vec<String>>, unknown: Option<bool>, pool_type: Option<&str>, is_monitoring: Option<bool>, hide_low_tvl: Option<f64>, hide_low_apr: Option<bool>, include_token_mints: Option<Vec<String>>, include_pool_token_pairs: Option<Vec<String>>, launchpad: Option<Vec<String>>) -> Result<models::PaginatedPoolResponse, Error<pools_api::FilterAndGetPoolInfoDeprecatedError>> {
        pools_api::filter_and_get_pool_info_deprecated(&self.config, page, size, version, filter, sort_key, order_by, pools_to_top, unknown, pool_type, is_monitoring, hide_low_tvl, hide_low_apr, include_token_mints, include_pool_token_pairs, launchpad).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_all_pool_configs(&self) -> Result<Vec<models::PoolConfigResponse>, Error<pools_api::GetAllPoolConfigsError>> {
        pools_api::get_all_pool_configs(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pools(&self, address: Option<Vec<String>>, unknown: Option<bool>, pool_type: Option<models::PoolTypeQueryParam>, is_monitoring: Option<bool>, hide_low_tvl: Option<f64>, hide_low_apr: Option<bool>, launchpad: Option<Vec<String>>) -> Result<Vec<models::PoolResponse>, Error<pools_api::GetPoolsError>> {
        pools_api::get_pools(&self.config, address, unknown, pool_type, is_monitoring, hide_low_tvl, hide_low_apr, launchpad).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pools_by_a_vault_lp(&self, pool_post_request: models::PoolPostRequest) -> Result<Vec<models::PoolResponse>, Error<pools_api::GetPoolsByAVaultLpError>> {
        pools_api::get_pools_by_a_vault_lp(&self.config, pool_post_request).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pools_metrics(&self) -> Result<models::AggregatePoolsMetrics, Error<pools_api::GetPoolsMetricsError>> {
        pools_api::get_pools_metrics(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_pools_with_farm(&self) -> Result<Vec<models::PoolResponse>, Error<pools_api::GetPoolsWithFarmError>> {
        pools_api::get_pools_with_farm(&self.config).await
    }
}
