// This file is generated by scripts/generate-rust-client.ts. Do not edit.

#![allow(deprecated)]

use crate::dynamic_vault::client::*;
use meteora_dynamic_vault_api_generated::apis::{
    apy_api,
    vaults_api,
    virtual_price_api,
};
use meteora_dynamic_vault_api_generated::apis::Error;
use meteora_dynamic_vault_api_generated::models;

impl Apy {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_apy_state(&self, token_mint: &str) -> Result<models::ApyState, Error<apy_api::GetApyStateError>> {
        apy_api::get_apy_state(&self.config, token_mint).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_filter_apy_by_time_range(&self, token_mint: &str, start_timestamp: &str, end_timestamp: &str) -> Result<models::ApyState, Error<apy_api::GetFilterApyByTimeRangeError>> {
        apy_api::get_filter_apy_by_time_range(&self.config, token_mint, start_timestamp, end_timestamp).await
    }
}

impl Vaults {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_vault_addresses(&self) -> Result<Vec<models::VaultAddress>, Error<vaults_api::GetVaultAddressesError>> {
        vaults_api::get_vault_addresses(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_vault_info(&self) -> Result<Vec<models::VaultState>, Error<vaults_api::GetVaultInfoError>> {
        vaults_api::get_vault_info(&self.config).await
    }

    #[allow(clippy::too_many_arguments)]
    pub async fn get_vault_state(&self, token_mint: &str) -> Result<models::VaultState, Error<vaults_api::GetVaultStateError>> {
        vaults_api::get_vault_state(&self.config, token_mint).await
    }
}

impl VirtualPrice {
    #[allow(clippy::too_many_arguments)]
    pub async fn get_virtual_price(&self, token_mint: &str, strategy: &str) -> Result<Vec<models::VirtualPrice>, Error<virtual_price_api::GetVirtualPriceError>> {
        virtual_price_api::get_virtual_price(&self.config, token_mint, strategy).await
    }
}
